# -*- coding: utf-8 -*-
#

import os
from os.path import join
racine = 'F:\ARMA2\PBO d\'origine\modules'

def ecrire(p,f):
    fsortie = open ("..\out\\" + f + ".txt","w")
    fsortie.write ("// =============================//\n")
    fsortie.write ("// list generated by DocArmaFnc \n")
    fsortie.write ("// a Z tool\n")
    fsortie.write ("// z_arma@hotmail.com\n")
    fsortie.write ("// =============================//\n")
    fsortie.write ("\n")
 #   print p
    for i in p:
        fsortie.write(i + "\n")
    fsortie.close

def listerep(p):
    liste = []
    for root, dirs, files in os.walk(p, topdown=False):
        for name in files:
            if "sqf" in name:
                nomfic =  join(root,name)
                if "scripts" in nomfic:
                    liste.append(nomfic)
    return liste

def mergefile(p):
    result = []
    module = ""
    modulep = ""
    for i in p:
        module = i.replace(racine,"")
        module = module.replace("\\", "/").split("/")[1]
        print module
        if module != modulep:
            if modulep:            
                ecrire(result,modulep)
            modulep = module
            result = []
            result.append(">>>>>>> MODULE >>>>>>> " + modulep)                   
        f = open(i,"r")
        f.readlines
        for l in f:
            if "scriptName" in l:
                result.append("<<< SCRIPT <<< " + l)
            else:
                result.append(l)
        f.close
    return result


os.chdir("out")
mergefile(listerep(racine)) 
